Repository certtools/intelmq-manager, pull requests merged in 2021-08, with the labels that each got.

#273 BUG: fix saving new bots
  CHANGELOG.md
  intelmq_manager/static/js/defaults.js
Labels: bug, component: configuration

#270 Fixes
  intelmq_manager/static/js/configs.js
  intelmq_manager/static/js/defaults.js
  intelmq_manager/static/js/intelmq-manager.js
  intelmq_manager/static/js/management.js
  intelmq_manager/static/js/monitor.js
  intelmq_manager/static/js/network-configuration.js
  intelmq_manager/static/js/positions.js
  intelmq_manager/static/js/runtime.js
  intelmq_manager/static/js/sb-admin-2.js
  intelmq_manager/static/js/static.js
  setup.py
Labels: bug, component: configuration, packaging

#274 Open documentation in a new window/tab
  intelmq_manager/templates/configs.mako
Labels: bug, component: configuration

#277 BUG: login: show error message from api
  CHANGELOG.md
  intelmq_manager/static/js/static.js
Labels: bug, user experience

#276 Various fixes
  intelmq_manager/static/js/configs.js
  intelmq_manager/static/js/monitor.js
  intelmq_manager/static/js/network-configuration.js
  intelmq_manager/static/js/static.js
Labels: enhancement, component: configuration, user experience, security
